### ISSUE TITLE
Not compatible with the ordering rule of Airbnb

### ISSUE THREAD

**Issue by joepio** [tylerbuchea/badass-react-snippets#3]
First of all: thanks for sharing!

The [Airbnb styleguide](https://github.com/airbnb/javascript/tree/master/react#ordering) requires the propTypes and defaultProps to be defined in the top of the file and linked to the class at the bottom of the file, like this:

```
const propTypes = {
  id: PropTypes.number.isRequired,
};

class Link extends React.Component {
}

Link.propTypes = propTypes;
```

But this package does this:

```
class Link extends React.Component {
}

Link.propTypes = {
  id: PropTypes.number.isRequired,
};
```

Most developers who use the Airbnb linter also want to adhere to the Airbnb styelguide. Therefore, I suggest to use the first pattern instead of the second.

**Comment by tylerthebuildor** [comment]
Thanks for the heads up @joepsz I was planning on updating the snippets soon anyhow, so this will be a good excuse.

**Comment by tylerthebuildor** [comment]
Just updated to 1.1.0 hope you like the changes 😄

**Comment by joepio** [comment]
Great work, thanks!
